[window]
padding = { x = 20, y = 20 }
dynamic_padding = true
decorations = "none"
# Since you have Picom, opacity here allows the blur to work
opacity = 0.85
blur = true

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Bold" }
size = 9.0

[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"

[colors.normal]
black =   "#15161e"
red =     "#f7768e"
green =   "#9ece6a"
yellow =  "#e0af68"
blue =    "#7aa2f7"
magenta = "#bb9af7"
cyan =    "#7dcfff"
white =   "#a9b1d6"

[colors.bright]
black =   "#414868"
red =     "#f7768e"
green =   "#9ece6a"
yellow =  "#e0af68"
blue =    "#7aa2f7"
magenta = "#bb9af7"
cyan =    "#7dcfff"
white =   "#c0caf5"

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "Always" }